- name: Deploy Docker App
  hosts: all
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop old container if exists
      shell: docker stop ravi-app || true

    - name: Remove old container if exists
      shell: docker rm ravi-app || true

    - name: Pull latest Docker image
      shell: docker pull ravijaiswal230392/ravi:latest

    - name: Run Docker container
      shell: docker run -d -p 80:80 --name ravi-app ravijaiswal230392/ravi:latest