name: Deploy My website

on:
  push:
    branches:
    - "**"
jobs:
    docker-build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            -name: Build Docker Image
              run: |
                docker build -t sujal

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: Set up SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.KEY }}" > ~/.ssh/SUJAL_SSH
                chmod 600 ~/.ssh/SUJAL_SSH
                ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

            - name: Copy files via SSH
              run: |
                scp -i ~/.ssh/SUJAL_SSH sites/sujal/index.html ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/sujal