name: Provision Nginx Server

on:
  push:
    branches:
      - "bench-natak"
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Target Server IP Address"
        required: false
        type: string
      ssh_user:
        description: "SSH User"
        required: false
        type: string
        default: "ubuntu"

jobs:
  provision-nginx:
    name: Run Ansible Playbook
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ inputs.server_ip || secrets.SAMBANDHA_SERVER_HOST }}
      SSH_USER: ${{ inputs.ssh_user || 'ubuntu' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SAMBANDHA_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        working-directory: ./infra/ansible/nginx/nginx
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          echo "[all]" > inventory.ini
          echo "$SERVER_IP ansible_user=$SSH_USER ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini
          ansible all -i inventory.ini -m ping
          ansible-playbook -i inventory.ini playbook.yml
