name: Provision Nginx Server Shothai

on:
  workflow_dispatch:
    inputs:
      server_ip:
        description: "Target Server IP Address"
        required: true
      ssh_user:
        description: "SSH User"
        required: true
        default: "ubuntu"
      ssh_password:
        description: "SSH Password"
        required: true

jobs:
  deploy:
    name: Run Ansible Playbook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Create inventory
        run: |
          echo "[web]" > inventory.ini
          echo "${{ github.event.inputs.server_ip }} ansible_user=${{ github.event.inputs.ssh_user }} ansible_ssh_pass=${{ github.event.inputs.ssh_password }}" >> inventory.ini

      - name: Run Playbook
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook \
          -i inventory.ini \
          infra/ansible/deploy-site.yml