name: Docker build & deploy

on:
  push:
    branches:
      - feature/pratyush

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: neocancode
          password: ${{ secrets.PRATYUSH_DOCKER_KEY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t neocancode/devops-class:latest .
          docker push neocancode/devops-class:latest

  deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: eef1df54591c.mylabserver.com
          username: ${{ secrets.PRATYUSH_SERVER_USERNAME }}
          key: ${{ secrets.PRATYUSH_SSH_KEY}}
          source: "sites/pratyush/index.html"
          target: /var/www/html/pratyush/
          strip_components: 2