name: Deploy My website

on:
  push:
    branches:
      - "feature/pravesh"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: create deploy directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: pravesh
          key: ${{ secrets.PRAVESH }}
          port: 22
          script: mkdir -p /var/www/html/pravesh

      - name: copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: pravesh
          key: ${{ secrets.PRAVESH }}
          port: 22
          source: "sites/pravesh/index.html"
          strip_components: 2
          target: "/var/www/html/pravesh/"