name: Deploy Static Website

on:
  push:
    branches:
      - feature/prayug
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker build
        run: |
          docker build -t prayug .

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: eef1df54591c.mylabserver.com
          username: root
          key: ${{ secrets.PRAYUG }}
          source: "sites/prayug/index.html"
          target: /var/www/html/prayug/
          strip_components: 2