name: Deploy bench01 website

on:
  push:
    branches:
      - bench-mates

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Copy files via SCP
        uses: appleboy/scp-action@v1
        with:
          host: eef1df54591c.mylabserver.com
          username: ${{ secrets.BENCH01 }}
          key: ${{ secrets.PRAVESH }}
          source: "./*"
          target: /opt/bench-01
      - name: Run Docker Compose on remote server
        run: |
          # Create SSH directory
          mkdir -p ~/.ssh

          # Write SSH key to file
          echo "${{ secrets.PRAVESH }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Add remote host to known_hosts to avoid prompt
          ssh-keyscan -H eef1df54591c.mylabserver.com >> ~/.ssh/known_hosts

          # Run Docker Compose remotely
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.BENCH01 }}@eef1df54591c.mylabserver.com \
            "cd /opt/bench-01 && docker compose up -d"