name: Deploy My website

on:
  push:
    branches:
      - feature/deepa

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_D }}
          password: ${{ secrets.DOCKER_SECRET_D }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME_D }}/devops-class:latest .
          docker push ${{ secrets.DOCKER_USERNAME_D }}/devops-class:latest

  deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "sites/deepa/index.html"
          target: /var/www/html/deepa/
          strip_components: 2

# 