name: Deploy My Website

on:
  push:
    branches:
      - feature/ritika

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Show files (debug step)
      - name: List files
        run: ls -la

      # 3. Docker build
      - name: Build Docker image
        run: |
          docker build -t trainer .

  deploy:
    runs-on: ubuntu-latest
    needs: build   # run only after build success

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # 3. Deploy files via SCP
      - name: Deploy to server
        run: |
          scp -i ~/.ssh/id_rsa -r sites/ritika/index.html \
          ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/ritika