name: Deploy My website

on:
  push:
    branches:
      - "feature/rijen"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          scp -i ~/.ssh/id_rsa sites/rijen/index.html \
          ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/index.html

      - name: Move to web root
        run: |
          ssh -i ~/.ssh/id_rsa \
          ${{ secrets.USERNAME }}@${{ secrets.HOST }} \
          "sudo mv ~/index.html /var/www/html/index.html"
