name: Deploy rijen's website

on:
  push:
    branches:
      - "feature/rijen"

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rezenn
          password: ${{ secrets.RIJEN_DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t rezenn/rijen:latest .
          docker push rezenn/rijen:latest

  deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RIJEN_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy files via SCP
        run: |
          scp -i ~/.ssh/id_rsa sites/rijen/index.html \
            ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/rijen/
