name: Deploy Sambandha's website

on:
  push:
    branches:
      - "features/sambandha"
jobs:
  docker build and push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SAMBANDHA_DOCKER_USERNAME }}
          password: ${{ secrets.SAMBANDHA_DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./sites/sambandha
          push: true
          tags: ${{ secrets.SAMBANDHA_DOCKER_USERNAME }}/my-site-sambandha:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy files via SSH
        run: |
          scp -i ~/.ssh/id_rsa sites/sambandha/index.html ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/trainer
