name: Natak Security Scan

on:
  push:
    branches:
      - "bench-natak"

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep scan --config auto --error ./sites/natak

  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: ./sites/natak
          severity: HIGH,CRITICAL
          exit-code: 1
